apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
  namespace: spydle
spec:
  replicas: 1  # Scalable via HPA
  template:
    spec:
      containers:
        - name: matchmaker
          env:
            - name: ENV
              value: "dev"
