apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: spydle-fleet
  namespace: spydle
spec:
  replicas: 4  # Initial idle GameServers
  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic  # Agones assigns a free port
          containerPort: 7654  # Netty server port
          protocol: UDP
      health:
        initialDelaySeconds: 60
        periodSeconds: 15
        failureThreshold: 3
      sdkServer:
        logLevel: Info
      template:
        metadata:
          labels:
            app: gameserver
        spec:
          containers:
            - name: gameserver
              image: gameserver:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: REDIS_HOST
                  value: redis
                - name: REDIS_PORT
                  value: "6379"
                - name: GAME_HOST_PORT
                  value: "7654"
                - name: AGONES_HOST_PORT
                  value: "9357"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "200m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
