apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- ingress/nginx-chart.yaml
- ingress/nginx-crds.yaml
- redis/redis-deployment.yaml
- redis/redis-service.yaml
- redis/redis-networkpolicy.yaml
- matchmaker/matchmaker-deployment.yaml
- matchmaker/matchmaker-service.yaml
- matchmaker/matchmaker-hpa.yaml
# For some reason, K3s does not like this network policy
#- matchmaker/matchmaker-networkpolicy.yaml
- gameserver/gameserver-fleet.yaml
- gameserver/fleet-autoscaler.yaml
#- gameserver/gameserver-networkpolicy.yaml
- ingress/ingress.yaml
