openapi: 3.0.0
info:
  title: Matchmaker REST API
  version: 0.0.1
paths:
  /autoscale:
    post:
      operationId: autoscale
      summary: Autoscale target for Agones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoscaleRequestModel'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoscaleResponseModel'
  /create-game:
    post:
      operationId: createGame
      summary: Create (allocate) new agones gameserver to client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRequestModel'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGameResponseModel'
components:
  schemas:
    AutoscaleRequestModel:
      type: object
      required: [request]
      properties:
        request:
          type: object
          required: [uid, name, namespace, status]
          properties:
            uid:
              type: string
            name:
              type: string
            namespace:
              type: string
            status:
              type: object
              required: [replicas, allocatedReplicas]
              properties:
                replicas:
                  type: integer
                readyReplicas:
                  type: integer
                reservedReplicas:
                  type: integer
                allocatedReplicas:
                  type: integer
        response:
          type: object
    AutoscaleResponseModel:
      type: object
      required: [response]
      properties:
        response:
          type: object
          required: [scale]
          properties:
            scale:
              type: object
              required: [replicas]
              properties:
                replicas:
                  type: integer
    CreateGameRequestModel:
      type: object
      required: [clientId]
      properties:
        clientId:
          type: string
    CreateGameResponseModel:
      type: object
      required: [gameServer]
      properties:
        gameServer:
          $ref: '#/components/schemas/GameServerInfoModel'
    GameServerInfoModel:
      type: object
      required: [address, port, gameServerName]
      properties:
        address:
          type: string
        port:
          type: integer
        gameServerName:
          type: string