apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matchmaker-ingress
  namespace: spydle
spec:
  ingressClassName: nginx
  rules:
    - host: spydle.kailo.ca  # Replace with your domain
      http:
        paths: # Do not expose autoscale
          - path: /create-game
            pathType: Prefix
            backend:
              service:
                name: matchmaker-service
                port:
                  number: 8080
          - path: /join-game
            pathType: Prefix
            backend:
              service:
                name: matchmaker-service
                port:
                  number: 8080
          - path: /list-games
            pathType: Prefix
            backend:
              service:
                name: matchmaker-service
                port:
                  number: 8080
