apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: matchmaker/matchmaker-hpa.yaml
- path: matchmaker/matchmaker-deployment.yaml
- path: gameserver/gameserver-fleet.yaml
