apiVersion: "agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: spydle-fleet-autoscaler
  namespace: spydle
spec:
  fleetName: spydle-fleet
  policy:
    type: Webhook
    webhook:
      service:
        name: matchmaker-service
        namespace: spydle
        path: /autoscale
        port: 8080